# Generated by Django 4.0.6 on 2022-08-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticias/descarga.png', null=True, upload_to='noticias'),
        ),
    ]
